POST https://api.iso5geducacional.com.br/api/v1/pagamento/webhook
Content-Type: application/json

{
  "id": "hook_oy7W5dSy1U0AwrJB",
  "account": {
    "id": "acc_1rpVl1KtPrIeEjnv",
    "name": "UNINESP ()"
  },
  "type": "order.paid",
  "created_at": "2026-08-24T11:21:49.1407663Z",
  "data": {
    "amount": 38700,
    "charges": [
      {
        "amount": 38700,
        "code": "3120",
        "created_at": "2026-08-20T20:13:18",
        "currency": "BRL",
        "customer": {
          "created_at": "2026-01-06T20:28:59",
          "delinquent": false,
          "document": "03919182227",
          "document_type": "cpf",
          "email": "m.claraboy@hotmail.com",
          "id": "cus_o639YgaULaTqpPGR",
          "name": "MARIA CLARA MARINHO BOY",
          "phones": {
            "home_phone": {
              "area_code": "22",
              "country_code": "55",
              "number": "988198927"
            }
          },
          "type": "individual",
          "updated_at": "2026-01-06T20:28:59"
        },
        "gateway_id": "4523766234",
        "id": "ch_4wLBmVQCzf0L7rpb",
        "last_transaction": {
          "amount": 38700,
          "antifraud_response": {},
          "bank": "198",
          "barcode": "https://api.pagar.me/core/v5/transactions/tran_VKQeABgUpPfrGlJg/barcode",
          "created_at": "2026-08-24T11:21:38",
          "document_number": "4523766234",
          "due_at": "2026-08-24T23:59:59",
          "gateway_id": "4523766234",
          "gateway_response": {},
          "id": "tran_w3Lg2lC8QhKrVAla",
          "instructions": "Pagar até o vencimento. \n Curso: DIREITO DO TRABALHO E PROCESSO DO TRABALHO - UNE",
          "line": "19790000054156980877101729978245115480000038700",
          "metadata": {},
          "nosso_numero": "4523766234",
          "paid_amount": 38700,
          "paid_at": "2026-08-24T11:21:38",
          "pdf": "https://api.pagar.me/1/boletos/live_cmt1yjw2pepkm0lm5mkbjjil4?format=pdf",
          "qr_code": "https://api.pagar.me/core/v5/transactions/tran_VKQeABgUpPfrGlJg/qrcode",
          "status": "paid",
          "success": true,
          "transaction_type": "boleto",
          "type": "DM",
          "updated_at": "2026-08-24T11:21:38",
          "url": "https://api.pagar.me/1/boletos/live_cmt1yjw2pepkm0lm5mkbjjil4"
        },
        "paid_amount": 38700,
        "paid_at": "2026-08-24T11:21:38",
        "payment_method": "boleto",
        "status": "paid",
        "updated_at": "2026-08-24T11:21:38"
      }
    ],
    "checkouts": [],
    "closed": true,
    "closed_at": "2026-08-20T20:13:18",
    "code": "3120",
    "created_at": "2026-08-20T20:13:18",
    "currency": "BRL",
    "customer": {
      "created_at": "2026-01-06T20:28:59",
      "delinquent": false,
      "document": "03919182227",
      "document_type": "cpf",
      "email": "m.claraboy@hotmail.com",
      "id": "cus_o639YgaULaTqpPGR",
      "name": "MARIA CLARA MARINHO BOY",
      "phones": {
        "home_phone": {
          "area_code": "22",
          "country_code": "55",
          "number": "988198927"
        }
      },
      "type": "individual",
      "updated_at": "2026-01-06T20:28:59"
    },
    "id": "or_Q2G5vjUyvuYX59rm",
    "items": [
      {
        "amount": 38700,
        "code": "3120",
        "created_at": "2026-08-20T20:13:18",
        "description": "DIREITO DO TRABALHO E PROCESSO DO TRABALHO",
        "id": "oi_DXzGpXkibT8wKMEP",
        "quantity": 1,
        "status": "active",
        "type": "product",
        "updated_at": "2026-08-20T20:13:18"
      }
    ],
    "status": "paid",
    "updated_at": "2026-08-24T11:21:38"
  }
}